server:
  port: 8083
spring:
  thymeleaf:
    cache: false

dubbo:
  application:
    name: web-search
  registry:
    address: zookeeper://192.168.40.166:2181
  consumer:
    check: false
    timeout: 30000
