spring:
  datasource:
    url: jdbc:mysql:///shop1909?serverTimezone=GMT%2B8
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.40.166
    username: admin
    password: admin
    virtual-host: /admin
    port: 5672
dubbo:
  application:
    name: service-goods
  registry:
    address: zookeeper://192.168.40.166:2181
  protocol:
    port: -1
  consumer:
    check: false
  provider:
    timeout: 30000

