dubbo:
  application:
    name: user-service
  registry:
    address: zookeeper://192.168.40.166:2181
  protocol:
    port: -1

spring:
  datasource:
    url: jdbc:mysql:///shop1909?serverTimezone=GMT%2B8
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
